conn system/manager
/
 create user khadim identified by khadims;
/
 grant connect,resource to khadim;
/
conn khadim/khadims;
/
create table login(USERNAME  VARCHAR2(20) primary key,PASSWORD VARCHAR2(20) not null);
/
insert into login values('admin',11111);
/
 create table empd(EMPCODE VARCHAR2(15) primary key,POST VARCHAR2(15),NAME VARCHAR2(20) NOT NULL,FATHERNAME VARCHAR2
(20),EMAILID VARCHAR2(20),AADHARNO NUMBER(12),ADDRESS VARCHAR2(40),JDATE DATE,USERNAME VARCHAR2(20),PASSWORD VARCHAR2(20
),MOBILENO NUMBER);
/
create table reail_INFO(NAME VARCHAR2(30),ADDRESS VARCHAR2(40),OTHERNAME VARCHAR2(30),EMAIL VARCHAR2(30),
PHONE NUMBER(10),TOLLFREE  VARCHAR2(18),STORETYPE  VARCHAR2(40));
/
create table customer_detail(C_ID VARCHAR2(10) primary key,CNAME VARCHAR2(20) NOT NULL,MOBILENO NUMBER(11),ADHARNO
NUMBER(13),EMAILID VARCHAR2(20),ADDRESS VARCHAR2(40), BANKACC NUMBER(15),PREDUES NUMBER);
/

 create table distributor_detail(D_ID VARCHAR2(10) primary key,DNAME VARCHAR2(20) NOT NULL,MOBILENO NUMBER(11),GSTNO
 VARCHAR2(15) not null,TINNO VARCHAR2(10),ADHARNO NUMBER(13),EMAILID VARCHAR2(20),ADDRESS VARCHAR2(40),BANKACC NUMBER(15
),PREDUES NUMBER);
/
 create table item_entry(ITEMTYPE VARCHAR2(15) NOT NULL,ITEMCODE VARCHAR2(22) primary key,DISCRIPTION VARCHAR2(30) NOT NULL,PUNIT NUMBER,PCOLOR VARCHAR2(10),PSIZE VARCHAR2(15) NOT NULL,PBRAND VARCHAR2(15) NOT NULL,PCATEGORY VARCHAR2(10),SOLE VARCHAR2(15),MRP NUMBER(7,2) NOT NULL,CGST NUMBER(6,2),SGST NUMBER(6,2),COSTPRICE NUMBER(7,2),ODIS NUMBER(6,2),TDIS NUMBER(7,2));
/
CREATE TABLE ORDER_CHAL (OINVOICE VARCHAR(15) PRIMARY KEY,IDATE DATE,DNAME VARCHAR(20) NOT NULL,DIS_ID VARCHAR(10) NOT NULL,MOBILENO NUMBER(12),ADHARNO VARCHAR(15),GST VARCHAR(16),PROTYPE VARCHAR(20),PROCODE VARCHAR(30),PSIZE VARCHAR(15),PUNIT NUMBER(4),DISO NUMBER(3),COSTPRICE DECIMAL(9,2),MRP DECIMAL(9,2),TOLAMT DECIMAL(9,2),TDIS DECIMAL(7,2),NETAMT DECIMAL(9,2),PAYMODE VARCHAR(20),ADVPAID DECIMAL(9,2),itol DECIMAL(9,2));
/
create table instruction(oins varchar(100),sins varchar(100),eins varchar(100));
/
 create table pro_report(inno varchar(20) ,protype varchar(10),procode number(15),psize varchar(15),qty number(5),dis number(5),mrp number(7),tolprice number);

insert into instruction values('You must attach a copy of the order confirmation or other evidence of your purchase',' Please note that refunds can take up to 10 working days ','We expect you to dispatch the goods as soon as possible after you have given notice of withdrawal. You must return them within 30 days.');
/

CREATE TABLE Export (EINVOICE VARCHAR(15) PRIMARY KEY,EDATE DATE,CNAME VARCHAR(20) NOT NULL,CUS_ID VARCHAR(10) NOT NULL,MOBILENO NUMBER(12),PDUES  NUMBER(7,2),EMAIL_ID VARCHAR(16),LOCATION VARCHAR(16),TOLPRICE NUMBER(9,2),GTOL  NUMBER(9,2),TDIS DECIMAL(7,2),NETAMT DECIMAL(9,2),PAYMODE VARCHAR(20),DUES NUMBER(7,2),PAID DECIMAL(9,2));
/
 CREATE TABLE SALE (SINVOICE VARCHAR(15) PRIMARY KEY,SDATE DATE,CNAME VARCHAR(35) NOT NULL,MOBILENO NUMBER(12),TOLPRICE NUMBER(9,2),GTOL NUMBER(9,2),TDIS DECIMAL(7,2),NETAMT DECIMAL(9,2),PAYMODE VARCHAR(20),PAID DECIMAL(9,2));
/
 CREATE TABLE PRO_SALE(SINVOICE VARCHAR(15),PROTYPE VARCHAR(20),PROCODE NUMBER(15),PSIZE VARCHAR(18),QTY NUMBER(5),PDIS DECIMAL(7,2),DIS DECIMAL(6,2),MRP DECIMAL(7,2),SALEPRICE DECIMAL(7,2),TOLPRICE DECIMAL(7,2));
/

